version: '3.1'
services:
  db:
    image: mysql:5.7
    container_name: wordpress-mariadb
    networks:
      - wordpress_network
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    restart: unless-stopped
  wordpress:
    image: wordpress:last
    container_name: wordpress-app
    ports:
      - 8080:80
    networks:
      - wordpress_network
    depends_on:
      - db
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_HOST=${MYSQL_HOST}
    restart: unless-stopped
volumes:
  wordpress_data: {}
  db_data: {}
networks:
  wordpress_network: